name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Cache uv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Run tests
      run: |
        uv run pytest tests -v
      env:
        # Add any environment variables needed for tests
        SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
